### ISSUE TITLE
pyttsx3.init() gives ERROR 

### ISSUE THREAD

**Issue by rakeshsagalagatte** [nateshmbhat/pyttsx3#109]
- pyttsx3 is successfully installed , But `engine = pyttsx3.init()` throw errors  like this 
```
Traceback (most recent call last):
  File "/home/unknown/.local/lib/python3.8/site-packages/pyttsx3/__init__.py", line 20, in init
    eng = _activeEngines[driverName]
  File "/usr/lib/python3.8/weakref.py", line 131, in __getitem__
    o = self.data[key]()
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/unknown/.local/lib/python3.8/site-packages/pyttsx3/__init__.py", line 22, in init
    eng = Engine(driverName, debug)
  File "/home/unknown/.local/lib/python3.8/site-packages/pyttsx3/engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "/home/unknown/.local/lib/python3.8/site-packages/pyttsx3/driver.py", line 50, in __init__
    self._module = importlib.import_module(name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/unknown/.local/lib/python3.8/site-packages/pyttsx3/drivers/espeak.py", line 3, in <module>
    import ctypes
  File "/usr/lib/python3.8/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.7: cannot open shared object file: No such file or directory
```
- Can You please help me to figure it out

**Comment by nateshmbhat** [comment]
The error seems to be coming from the underlying espeak driver. I don't understand why this happens for only some systems 😕😕

**Comment by utkarshMmishra** [comment]
try installing different version of pyttsx3
pip install pyttsx3=2.71

**Comment by rakeshsagalagatte** [comment]
![pyttsx3issues](https://user-images.githubusercontent.com/42493466/82354621-acfa4280-9a1e-11ea-93d5-c3e0b2ffc93d.png)
This time i changed my m/c to ubuntu 20 .. But same error i got :confused: :thinking:

**Comment by nateshmbhat** [comment]
Install espeak and check

**Comment by nateshmbhat** [comment]
libespeak

**Comment by rakeshsagalagatte** [comment]
![issuescleared](https://user-images.githubusercontent.com/42493466/82400409-de056200-9a74-11ea-8d08-6dad909be393.png)
Now it's working , And did you remove the speak() ?, it says like that..
Thanks @nateshmbhat  :blush: :+1: :smiley:
