### ISSUE TITLE
please  help me

### ISSUE THREAD

**Issue by naveed2020-new** [nateshmbhat/pyttsx3#123]
Traceback (most recent call last):
  File "C:\Users\naveed projects\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyttsx3\__init__.py", line 20, in init
    eng = _activeEngines[driverName]
  File "C:\Users\naveed projects\AppData\Local\Programs\Python\Python38-32\lib\weakref.py", line 131,
in __getitem__
    o = self.data[key]()
KeyError: 'sapi5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:/NAVEED FOLDER/all projects/project#55/jarvis.py", line 3, in <module>
    engine = pyttsx3.init('sapi5')
  File "C:\Users\naveed projects\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyttsx3\__init__.py", line 22, in init
    eng = Engine(driverName, debug)
  File "C:\Users\naveed projects\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyttsx3\engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "C:\Users\naveed projects\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyttsx3\driver.py", line 50, in __init__
    self._module = importlib.import_module(name)
  File "C:\Users\naveed projects\AppData\Local\Programs\Python\Python38-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\naveed projects\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyttsx3\drivers\sapi5.py", line 10, in <module>
    import pythoncom
ModuleNotFoundError: No module named 'pythoncom'

**Comment by nateshmbhat** [comment]
See this answer

https://stackoverflow.com/a/4145183/6665568

**Comment by nateshmbhat** [comment]
Did you try this? Did it solve your issue?
Please let us know... N

**Comment by nateshmbhat** [comment]
Fixed in the latest release v.2.90
