### ISSUE TITLE
Error after compilation

### ISSUE THREAD

**Issue by SwayamTakkamore** [nateshmbhat/pyttsx3#146]
**I am using Python 3.8.2**

import pyttsx3

engine = pyttsx3.init('sapi5')
voices = engine.getProperty('voices')
print(voices)

def speak(audio):
pass

**I am being got an error.**

Traceback (most recent call last):
File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\pyttsx3_init_.py", line 20, in init
eng = _activeEngines[driverName]
File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\weakref.py", line 131, in getitem
o = self.datakey
KeyError: 'sapi5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "c:\Users\admin\Desktop\Python\Jarvis with python_CodeWithHarry\jarvis.py", line 3, in
engine = pyttsx3.init('sapi5')
File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\pyttsx3_init_.py", line 22, in init
eng = Engine(driverName, debug)
File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\pyttsx3\engine.py", line 30, in init
self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\pyttsx3\driver.py", line 50, in init
self.module = importlib.import_module(name)
File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\importlib_init.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 1014, in _gcd_import
File "", line 991, in _find_and_load
File "", line 975, in _find_and_load_unlocked
File "", line 671, in _load_unlocked
File "", line 783, in exec_module
File "", line 219, in _call_with_frames_removed
File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\pyttsx3\drivers\sapi5.py", line 3, in
import win32com.client
ModuleNotFoundError: No module named 'win32com'

**Please solve it**

**Comment by AmitKarnam** [comment]
I am using python 3.9 and pyttsx3 version  2.9. The following code seems to work for me.

from pyttsx3 import *
speak("hello world")

**Comment by AmitKarnam** [comment]
With that version of python try and use pyttsx3 2.7.1 it should work

**Comment by SwayamTakkamore** [comment]
Yes, it will definitely work...
