### ISSUE TITLE
Pyttsx3 Error

### ISSUE THREAD

**Issue by LaKhWaN** [nateshmbhat/pyttsx3#165]
Idk what's the prblm i m just doing 
`import pyttsx3
engine = pyttsx3.init()
engine.say("I will speak this text")
engine.runAndWait()
`
dunno why
Traceback (most recent call last):
  File "F:\Python\lib\site-packages\pyttsx3\__init__.py", line 20, in init
    eng = _activeEngines[driverName]
  File "F:\Python\lib\weakref.py", line 134, in __getitem__
    o = self.data[key]()
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Python\lib\site-packages\win32com\client\dynamic.py", line 81, in _GetGoodDispatch
    IDispatch = pythoncom.connect(IDispatch)
pywintypes.com_error: (-2147221005, 'Invalid class string', None, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\LaKhWaN\Documents\Mega Python Project\check.py", line 2, in <module>
    engine = pyttsx3.init()
  File "F:\Python\lib\site-packages\pyttsx3\__init__.py", line 22, in init
    eng = Engine(driverName, debug)
  File "F:\Python\lib\site-packages\pyttsx3\engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "F:\Python\lib\site-packages\pyttsx3\driver.py", line 52, in __init__
    self._driver = self._module.buildDriver(weakref.proxy(self))
  File "F:\Python\lib\site-packages\pyttsx3\drivers\sapi5.py", line 23, in buildDriver
    return SAPI5Driver(proxy)
  File "F:\Python\lib\site-packages\pyttsx3\drivers\sapi5.py", line 28, in __init__
    self._tts = win32com.client.Dispatch('SAPI.SPVoice')
  File "F:\Python\lib\site-packages\win32com\client\__init__.py", line 95, in Dispatch
    dispatch, userName = dynamic._GetGoodDispatchAndUserName(dispatch,userName,clsctx)
  File "F:\Python\lib\site-packages\win32com\client\dynamic.py", line 98, in _GetGoodDispatchAndUserName
    return (_GetGoodDispatch(IDispatch, clsctx), userName)
  File "F:\Python\lib\site-packages\win32com\client\dynamic.py", line 83, in _GetGoodDispatch
    IDispatch = pythoncom.CoCreateInstance(IDispatch, None, clsctx, pythoncom.IID_IDispatch)
pywintypes.com_error: (-2147221005, 'Invalid class string', None, None)

many pppls getting this error please sort this out thanks a lot

**Comment by nateshmbhat** [comment]
Dummy is not a valid driver. It will not produce sound if dummy is used anyway.

**Comment by nateshmbhat** [comment]
Make sure u have sapi5 driver in windows. Install it if you don't have already.

**Comment by TotallyAProgrammer** [comment]
Please ensure that you have pypiwin32 installed, along with SAPI5 installed. SAPI5 should be installed by default so you shouldn't have to worry about it, but pypiwin32 will help if it isn't installed.

**Comment by nateshmbhat** [comment]
Closing until furthur response.
