### ISSUE TITLE
an error in a virtual environment happend

### ISSUE THREAD

**Issue by saaaya-11** [nateshmbhat/pyttsx3#174]

**Comment by TotallyAProgrammer** [comment]
Have you updated anything python related recently?

**Comment by saaaya-11** [comment]
Thank you for your reply.
No, I haven’t. But since I got this error today, I have tried only reinstalling pyttsx3, and installing older version(2.7) so far... as mentioned before,,, it(the latest version) works in the “base “ environment...

**Comment by TotallyAProgrammer** [comment]
That is quite odd. What platform are you running on and which speech engine are you using? I wonder if this has something to do with some recent patches and feature additions I worked on

**Comment by saaaya-11** [comment]
I am running it on Anaconda Prompt, and using sapi5 because my pc is Windows one.
`import pyttsx3
engine = pyttsx3.init('sapi5') #the error occurs at this line
`
Detail of the error is below...
`Traceback (most recent call last):
  File "C:\Users\name\Anaconda3\envs\envStudy\lib\site-packages\pyttsx3\__init__.py", line 20, in init
    eng = _activeEngines[driverName]
  File "C:\Users\name\Anaconda3\envs\envStudy\lib\weakref.py", line 131, in __getitem__
    o = self.data[key]()
KeyError: 'sapi5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "untitled0.py", line 21, in <module>
    TextToSpeech_pyttsx3(text)
  File "untitled0.py", line 12, in TextToSpeech_pyttsx3
    engine = pyttsx3.init('sapi5')
  File "C:\Users\name\Anaconda3\envs\envStudy\lib\site-packages\pyttsx3\__init__.py", line 22, in init
    eng = Engine(driverName, debug)
  File "C:\Users\name\Anaconda3\envs\envStudy\lib\site-packages\pyttsx3\engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "C:\Users\name\Anaconda3\envs\envStudy\lib\site-packages\pyttsx3\driver.py", line 52, in __init__
    self._driver = self._module.buildDriver(weakref.proxy(self))
  File "C:\Users\name\Anaconda3\envs\envStudy\lib\site-packages\pyttsx3\drivers\sapi5.py", line 30, in buildDriver
    return SAPI5Driver(proxy)
  File "C:\Users\name\Anaconda3\envs\envStudy\lib\site-packages\pyttsx3\drivers\sapi5.py", line 35, in __init__
    self._tts = comtypes.client.CreateObject('SAPI.SPVoice')
  File "C:\Users\name\Anaconda3\envs\envStudy\lib\site-packages\comtypes\client\__init__.py", line 250, in CreateObject
    return _manage(obj, clsid, interface=interface)
  File "C:\Users\name\Anaconda3\envs\envStudy\lib\site-packages\comtypes\client\__init__.py", line 188, in _manage
    obj = GetBestInterface(obj)
  File "C:\Users\name\Anaconda3\envs\envStudy\lib\site-packages\comtypes\client\__init__.py", line 112, in GetBestInterface
    interface = getattr(mod, itf_name)
AttributeError: module 'comtypes.gen.SpeechLib' has no attribute 'ISpeechVoice'`

**Comment by TotallyAProgrammer** [comment]
Okay, so here is the issue:
SpeechLib is generated at runtime by comtypes.gen, if Windows updated SAPI, then the SAPI API could have changed.
Or, the API changed and has chosen that `sapi5` is no longer a valid engine.
The first issue would require a patch to pyttsx3, which I can do later tonight once I'm at my Windows computer.
The second issue is solvable by being more specific with what you want to do. In my code I do that like this:
`
engine = pyttsx3.init(driverName=None, debug=True)
`
That will tell pyttsx3 to automatically select a compatible TTS engine. If that fails you can also try this:
`
engine = pyttsx3.init(driverName='sapi5', debug=True)
`
If the error persists, or if I run into the same error tonight, I will work on a patch for pyttsx3. I don't know why this is happening, but I hope it has nothing to do with my recent patch, as I program in Python 3 and do not generally keep Python 2 in mind.
