### ISSUE TITLE
sapi5 ERROR

### ISSUE THREAD

**Issue by jaypatel2214** [nateshmbhat/pyttsx3#190]
Traceback (most recent call last):
  File "/home/jay/.local/lib/python3.9/site-packages/pyttsx3/__init__.py", line 20, in init
    eng = _activeEngines[driverName]
  File "/usr/lib/python3.9/weakref.py", line 134, in __getitem__
    o = self.data[key]()
KeyError: 'sapi5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jay/Desktop/Simple AI.py", line 6, in <module>
    engine = pyttsx3.init('sapi5')
  File "/home/jay/.local/lib/python3.9/site-packages/pyttsx3/__init__.py", line 22, in init
    eng = Engine(driverName, debug)
  File "/home/jay/.local/lib/python3.9/site-packages/pyttsx3/engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "/home/jay/.local/lib/python3.9/site-packages/pyttsx3/driver.py", line 50, in __init__
    self._module = importlib.import_module(name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/jay/.local/lib/python3.9/site-packages/pyttsx3/drivers/sapi5.py", line 1, in <module>
    import comtypes.client  # Importing comtypes.client will make the gen subpackage
ModuleNotFoundError: No module named 'comtypes'

**Comment by JahidFariz** [comment]
try again after installing **comtypes**
use the following command to install comtypes: **pip install comtypes**
this command only works on windows operating system.

**Comment by jaypatel2214** [comment]
> try again after installing **comtypes**
> use the following command to install comtypes: **pip install comtypes**
> this command only works on windows operating system.

thanks

**Comment by jaypatel2214** [comment]
thanks it helped

**Comment by ayushete02** [comment]
> try again after installing **comtypes** use the following command to install comtypes: **pip install comtypes** this command only works on windows operating system.

Its not working for me, Could you suggest another solution
