### ISSUE TITLE
Problems with macOS Big Sur and pyttsx3

### ISSUE THREAD

**Issue by wptmdoorn** [nateshmbhat/pyttsx3#192]
Hi everyone,

First of all - thank you for this great library, I have been using it (on Windows) for a long time and it is really great. Unfortunately I cannot get the library to work on my new Apple M1 laptop with macOS Big Sur. I am not completely sure where to go with in relation to the error message I am getting. 

System and software specifications:
```
macOS Big Sur version 11
Python 3.8.6  
pyttsx3 3.90  
pyobjc 7.10
```

For now, I am just trying out a fairly simple code snippet which is (unfortunately) not running:

```
import pyttsx3

engine = pyttsx3.init()
engine.save_to_file("test 1 2 3", 'test.mp3')
engine.runAndWait()  
```

This returns the following error:

```
Traceback (most recent call last):
  File "/Users/wptmdoorn/miniforge3/envs/mainenv/lib/python3.8/site-packages/pyttsx3/__init__.py", line 20, in init
    eng = _activeEngines[driverName]
  File "/Users/wptmdoorn/miniforge3/envs/mainenv/lib/python3.8/weakref.py", line 131, in __getitem__
    o = self.data[key]()
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wptmdoorn/Documents/Programmeren/Hobby/Projecten/pubmedtoaudio/pubmedtoaudio/test.py", line 3, in <module>
    engine = pyttsx3.init()
  File "/Users/wptmdoorn/miniforge3/envs/mainenv/lib/python3.8/site-packages/pyttsx3/__init__.py", line 22, in init
    eng = Engine(driverName, debug)
  File "/Users/wptmdoorn/miniforge3/envs/mainenv/lib/python3.8/site-packages/pyttsx3/engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "/Users/wptmdoorn/miniforge3/envs/mainenv/lib/python3.8/site-packages/pyttsx3/driver.py", line 50, in __init__
    self._module = importlib.import_module(name)
  File "/Users/wptmdoorn/miniforge3/envs/mainenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/wptmdoorn/miniforge3/envs/mainenv/lib/python3.8/site-packages/pyttsx3/drivers/nsss.py", line 2, in <module>
    from Foundation import *
  File "/Users/wptmdoorn/miniforge3/envs/mainenv/lib/python3.8/site-packages/Foundation/__init__.py", line 9, in <module>
    import CoreFoundation
  File "/Users/wptmdoorn/miniforge3/envs/mainenv/lib/python3.8/site-packages/CoreFoundation/__init__.py", line 9, in <module>
    import objc
  File "/Users/wptmdoorn/miniforge3/envs/mainenv/lib/python3.8/site-packages/objc/__init__.py", line 6, in <module>
    from . import _objc
ImportError: dlopen(/Users/wptmdoorn/miniforge3/envs/mainenv/lib/python3.8/site-packages/objc/_objc.cpython-38-darwin.so, 2): Symbol not found: _ffi_find_closure_for_code_np
  Referenced from: /Users/wptmdoorn/miniforge3/envs/mainenv/lib/python3.8/site-packages/objc/_objc.cpython-38-darwin.so
  Expected in: flat namespace
 in /Users/wptmdoorn/miniforge3/envs/mainenv/lib/python3.8/site-packages/objc/_objc.cpython-38-darwin.so
```

Analyzing this traceback it looks something related to `pyobjc` although I am not fully convinced. I have tried multiple versions of pyttsx3 and pyobjc but none of these combinations worked. Furthermore I have checked multiple solutions provided before on here, but also none of them worked (most of them were related to installing pyobjc). Would anybody have an idea what is going here?

Thanks a lot in advance. 
All the best, William

**Comment by willwade** [comment]
Fixed a while ago now. Thanks for logging this
