### ISSUE TITLE
Loop hangs when saving to file

### ISSUE THREAD

**Issue by 9mido** [nateshmbhat/pyttsx3#194]
In a multi-line txt file, I was trying to save each line of text into its own mp3 file. However, the loop hangs at line number 2. Someone on IRC was also able to reproduce the same problem with me. You may have to run it a few times to get it to happen. 

```
import time
import io

with io.open('file.txt', encoding='utf-8') as file:
    file = file.readlines()

import pyttsx3
engine = pyttsx3.init()
voices = engine.getProperty('voices')

number = 0
for line in file:
    time.sleep(5)
    number = number + 1
    print(number)
    print(line)
    engine.save_to_file(line, str(number) + ".mp3")
    engine.runAndWait()
    engine.stop()
```

Not sure what some of this stuff means from the output of this command but maybe that could help?

`python -m trace --trace YOURSCRIPT.py`

Traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.8/trace.py", line 756, in <module>
    main()
  File "/usr/lib/python3.8/trace.py", line 744, in main
    t.runctx(code, globs, globs)
  File "/usr/lib/python3.8/trace.py", line 450, in runctx
    exec(cmd, globals, locals)
  File "file.py", line 24, in <module>
    engine.runAndWait()
  File "/home/name/.local/lib/python3.8/site-packages/pyttsx3/engine.py", line 180, in runAndWait
    self.proxy.runAndWait()
  File "/home/name/.local/lib/python3.8/site-packages/pyttsx3/driver.py", line 192, in runAndWait
    self._driver.startLoop()
  File "/home/name/.local/lib/python3.8/site-packages/pyttsx3/drivers/espeak.py", line 124, in startLoop
    time.sleep(0.01)
```

```
espeak.py(112):         while self._looping:
espeak.py(113):             if first:
espeak.py(117):             if self._stopping and self._looping:
espeak.py(124):             time.sleep(0.01)
```

**Comment by dhruvchandel** [comment]
Put it in a limited time thread, and kill the thread if the program if it crosses a certain time limit anytime

**Comment by 9mido** [comment]
Not sure how to do that. Can you provide some example code?
