### ISSUE TITLE
sapi5 error in wsl ubuntu

### ISSUE THREAD

**Issue by Shuvadip-Ghosh** [nateshmbhat/pyttsx3#212]
I am currently running ubuntu in wsl my code works fine in windows but when I switch to wsl ubuntu it gives me this error
Please any help will be apreciated

`  File "/home/coder/.local/lib/python3.8/site-packages/pyttsx3/__init__.py", line 44, in init
    eng = _activeEngines[driverName]
  File "/usr/lib/python3.8/weakref.py", line 131, in __getitem__
    o = self.data[key]()
KeyError: 'sapi5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Maya_Features.py", line 9, in <module>
    engine = pyttsx3.init('sapi5')
  File "/home/coder/.local/lib/python3.8/site-packages/pyttsx3/__init__.py", line 46, in init
    eng = Engine(driverName, debug)
  File "/home/coder/.local/lib/python3.8/site-packages/pyttsx3/engine.py", line 52, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "/home/coder/.local/lib/python3.8/site-packages/pyttsx3/driver.py", line 75, in __init__
    self._module = importlib.import_module(name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/coder/.local/lib/python3.8/site-packages/pyttsx3/drivers/sapi5.py", line 3, in <module>
    import win32com.client
ModuleNotFoundError: No module named 'win32com'`

**Comment by AmitKarnam** [comment]
As far as I know SAPI5 is a voice recognition and synthesis provided by Microsoft. Starting with Windows XP, it ships as part of the Windows OS. 
In the docs it says for linux try this command
```voice recognition and synthesis provided by Microsoft. Starting with Windows XP, it ships as part of the Windows OS. If you are using a different OS```
