### ISSUE TITLE
Support CentOS 8 system?

### ISSUE THREAD

**Issue by Jzow** [nateshmbhat/pyttsx3#223]
I have no problem running on my native windows, but when I deploy to CentOS operating system, I can't find ffpmpeg

**Comment by Jzow** [comment]
Obviously, the yum source does not have ffpmpeg

**Comment by Jzow** [comment]
#41

**Comment by Jzow** [comment]
I installed ffmpeg by referring to the tutorial, but the running code is still wrong

```shell
[root@localhost TencentDemoBackend]# ffmpeg -version
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-44)
configuration: --enable-shared --prefix=/usr/local/ffmpeg
libavutil      56. 22.100 / 56. 22.100
libavcodec     58. 35.100 / 58. 35.100
libavformat    58. 20.100 / 58. 20.100
libavdevice    58.  5.100 / 58.  5.100
libavfilter     7. 40.101 /  7. 40.101
libswscale      5.  3.100 /  5.  3.100
libswresample   3.  3.100 /  3.  3.100

```

**Comment by Jzow** [comment]
error:

```python
Exception ignored on calling ctypes callback function: <bound method EspeakDriver._onSynth of <pyttsx3.drivers.espeak.EspeakDriver object at 0x7f6c267ce940>>
Traceback (most recent call last):
  File "/root/anaconda3/envs/tencentdemo/lib/python3.8/site-packages/pyttsx3/drivers/espeak.py", line 153, in _onSynth
    self._proxy.notify('started-word',
ReferenceError: weakly-referenced object no longer exists
sh: ffmpeg: 未找到命令
Exception ignored on calling ctypes callback function: <bound method EspeakDriver._onSynth of <pyttsx3.drivers.espeak.EspeakDriver object at 0x7f6c267ce940>>
Traceback (most recent call last):
  File "/root/anaconda3/envs/tencentdemo/lib/python3.8/site-packages/pyttsx3/drivers/espeak.py", line 171, in _onSynth
    self._proxy.notify('finished-utterance', completed=True)
ReferenceError: weakly-referenced object no longer exists
Internal Server Error: /api/text/
Traceback (most recent call last):
  File "/root/anaconda3/envs/tencentdemo/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/anaconda3/envs/tencentdemo/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/anaconda3/envs/tencentdemo/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/root/work/2022.01.26/iston_algorithm_v2/TencentDemoBackend/apps/iflytek/Audio.py", line 24, in textAndAudio
    upload(_urlname_)  # 文件上传至服务器
  File "/root/work/2022.01.26/iston_algorithm_v2/TencentDemoBackend/apps/iflytek/Audio.py", line 82, in upload
    files = {"file": open(f"./apps/iflytek/{str(path)}", "rb")}
FileNotFoundError: [Errno 2] No such file or directory: './apps/iflytek/1644992316.wav'

```

**Comment by willwade** [comment]
This is technically fixed. It was the espeak bugs. Please reopen if I'm wrong!
