### ISSUE TITLE
I'm getting an error like this, what to do?

### ISSUE THREAD

**Issue by scoder5** [nateshmbhat/pyttsx3#244]
Traceback (most recent call last):
  File "C:\Python\Python310\lib\site-packages\pyttsx3\__init__.py", line 20, in init
    eng = _activeEngines[driverName]
  File "C:\Python\Python310\lib\weakref.py", line 137, in __getitem__
    o = self.data[key]()
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Coding\Python\Jarvis_New\test.py", line 17, in <module>
    speak("Hello")
  File "D:\Coding\Python\Jarvis_New\test.py", line 13, in speak
    engine = pyttsx3.init()
  File "C:\Python\Python310\lib\site-packages\pyttsx3\__init__.py", line 22, in init
    eng = Engine(driverName, debug)
  File "C:\Python\Python310\lib\site-packages\pyttsx3\engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "C:\Python\Python310\lib\site-packages\pyttsx3\driver.py", line 52, in __init__
    self._driver = self._module.buildDriver(weakref.proxy(self))
  File "C:\Python\Python310\lib\site-packages\pyttsx3\drivers\sapi5.py", line 30, in buildDriver
    return SAPI5Driver(proxy)
  File "C:\Python\Python310\lib\site-packages\pyttsx3\drivers\sapi5.py", line 47, in __init__
    self.setProperty('voice', self.getProperty('voice'))
  File "C:\Python\Python310\lib\site-packages\pyttsx3\drivers\sapi5.py", line 90, in getProperty
    return self._tts.Voice.Id
_ctypes.COMError: (-2147221164, 'Class not registered', (None, None, None, 0, None))

**Comment by willwade** [comment]
pretty sure this is old.. cant replicate
