### ISSUE TITLE
Init error on very simple example code

### ISSUE THREAD

**Issue by orangefabri** [nateshmbhat/pyttsx3#257]
Hello. I'm using windows 11 and python 3.9.16

~~for your reference I'm using "Beta: Use Unicode UTF-8 for worldwide language support" on windows.~~
~~because some python module needed that.~~
<- I found that option unchecked after windows update

this is my code :

class SpeakService:
    def __init__(self):
        self.engine = pyttsx3.init('sapi5') 

    def speak(self, message):
        self.engine.say(message)
        self.engine.runAndWait()

and this is my error message when I tired to __init()__
:
C:\Users\xxxx\.conda\envs\xxxx\python.exe C:/Users/xxxx/PycharmProjects/xxxx/main.py
Traceback (most recent call last):
  File "C:\Users\xxxx\.conda\envs\xxxx\lib\site-packages\pyttsx3\__init__.py", line 20, in init
    eng = _activeEngines[driverName]
  File "C:\Users\xxxx\.conda\envs\xxxx\lib\weakref.py", line 137, in __getitem__
    o = self.data[key]()
KeyError: 'sapi5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xxxx\.conda\envs\xxxx\lib\tokenize.py", line 330, in find_cookie
    line_string = line.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xxxx\PycharmProjects\xxxx\main.py", line 179, in <module>
    mw = MainWindow()
  File "C:\Users\xxxx\PycharmProjects\xxxx\main.py", line 65, in __init__
    self.speak_service = SpeakService()
  File "C:\Users\xxxx\PycharmProjects\xxxx\main.py", line 27, in __init__
    self.engine = pyttsx3.init('sapi5')
  File "C:\Users\xxxx\.conda\envs\xxxx\lib\site-packages\pyttsx3\__init__.py", line 22, in init
    eng = Engine(driverName, debug)
  File "C:\Users\xxxx\.conda\envs\xxxx\lib\site-packages\pyttsx3\engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "C:\Users\xxxx\.conda\envs\xxxx\lib\site-packages\pyttsx3\driver.py", line 50, in __init__
    self._module = importlib.import_module(name)
  File "C:\Users\xxxx\.conda\envs\xxxx\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\xxxx\.conda\envs\xxxx\lib\site-packages\pyttsx3\drivers\sapi5.py", line 3, in <module>
    import win32com.client
  File "C:\Users\xxxx\.conda\envs\xxxx\lib\site-packages\win32com\__init__.py", line 6, in <module>
    import pythoncom
  File "C:\Users\xxxx\.conda\envs\xxxx\lib\site-packages\pythoncom.py", line 2, in <module>
    import pywintypes
  File "shibokensupport/signature/loader.py", line 61, in feature_imported
  File "shibokensupport/feature.py", line 137, in feature_imported
  File "shibokensupport/feature.py", line 148, in _mod_uses_pyside
  File "C:\Users\xxxx\.conda\envs\xxxx\lib\inspect.py", line 1024, in getsource
    lines, lnum = getsourcelines(object)
  File "C:\Users\xxxx\.conda\envs\xxxx\lib\inspect.py", line 1006, in getsourcelines
    lines, lnum = findsource(object)
  File "C:\Users\xxxx\.conda\envs\xxxx\lib\inspect.py", line 831, in findsource
    lines = linecache.getlines(file, module.__dict__)
  File "C:\Users\xxxx\.conda\envs\xxxx\lib\linecache.py", line 46, in getlines
    return updatecache(filename, module_globals)
  File "C:\Users\xxxx\.conda\envs\xxxx\lib\linecache.py", line 136, in updatecache
    with tokenize.open(fullname) as fp:
  File "C:\Users\xxxx\.conda\envs\xxxx\lib\tokenize.py", line 394, in open
    encoding, lines = detect_encoding(buffer.readline)
  File "C:\Users\xxxx\.conda\envs\xxxx\lib\tokenize.py", line 371, in detect_encoding
    encoding = find_cookie(first)
  File "C:\Users\xxxx\.conda\envs\xxxx\lib\tokenize.py", line 335, in find_cookie
    raise SyntaxError(msg)
SyntaxError: invalid or missing encoding declaration for 'C:\\Users\\xxxx\\.conda\\envs\\xxxx\\lib\\site-packages\\win32\\pywintypes39.dll'

Process finished with exit code 1

**Comment by orangefabri** [comment]
I tried this code but didn't work :

self.engine = pyttsx3.init()

**Comment by orangefabri** [comment]
and, for your reference, I'm using virtual envs. 

I think something blocks importing pythoncom and pywintypes.

pypiwin32 is already installed in my virtuenv.

**Comment by orangefabri** [comment]
I debugged my code and found " return _bootstrap._gcd_import(name[level:], package, level)" code generates error here :

def import_module(name, package=None):
    """Import a module.

    The 'package' argument is required when performing a relative import. It
    specifies the package to use as the anchor point from which to resolve the
    relative import to an absolute import.

    """
    level = 0
    if name.startswith('.'):
        if not package:
            msg = ("the 'package' argument is required to perform a relative "
                   "import for {!r}")
            raise TypeError(msg.format(name))
        for character in name:
            if character != '.':
                break
            level += 1
    return _bootstrap._gcd_import(name[level:], package, level)

**Comment by orangefabri** [comment]
and control center in my laptop has voice tab and I can play david or other voices.

and pypiwin32 is installed in my virtual env, as I said above

**Comment by orangefabri** [comment]
I'm using SpeakService class in PySide6 main UI.

**Comment by orangefabri** [comment]
I found today that outside the QApplication, in python console, pyttsx3 runs well(I could make it say hello)

if I use this in PySide6 UI, it generates error.

**Comment by orangefabri** [comment]
to regenerate this error, you can simply run this in PySide6 in virtual environment of anaconda.

I wonder why this happens and hope it to be repaired

**Comment by orangefabri** [comment]
problem solved.

**Comment by duolabmeng6** [comment]
I'm sorry to ask, but how did you solve it?

**Comment by orangefabri** [comment]
> I'm sorry to ask, but how did you solve it?

I don't remember exactly, but maybe I memo somewhere in the code. if you want, I can check my memo
