### ISSUE TITLE
pyttsx3\engine.py", line 177, in runAndWait     raise RuntimeError('run loop already started')

### ISSUE THREAD

**Issue by QGB** [nateshmbhat/pyttsx3#262]
```
Traceback (most recent call last):
  File "C:/QGB/babun/cygwin/bin\qgb\U.py", line 2328, in execStrResult
    exec(source, globals, locals)
  File "<string>", line 1, in <module>
  File "C:/QGB/babun/cygwin/bin\qgb\U.py", line 7540, in tts_speak
    engine.runAndWait()
  File "C:\QGB\Anaconda3\lib\site-packages\pyttsx3\engine.py", line 177, in runAndWait
    raise RuntimeError('run loop already started')
RuntimeError: run loop already started
```

**Comment by nosson-p** [comment]
I think your trying to run it while it is already being run
