### ISSUE TITLE
class WinFunctionType(_CFuncPtr): TypeError: item 1 in _argtypes_ passes a union by value, which is unsupported.

### ISSUE THREAD

**Issue by Vilas0** [nateshmbhat/pyttsx3#264]
Traceback (most recent call last):
  File "C:\Users\DC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyttsx3\__init__.py", line 20, in init
    eng = _activeEngines[driverName]
  File "C:\Users\DC\AppData\Local\Programs\Python\Python37-32\lib\weakref.py", line 137, in __getitem__
    o = self.data[key]()
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\DC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyttsx3\drivers\sapi5.py", line 3, in <module>
    from comtypes.gen import SpeechLib  # comtypes
ImportError: cannot import name 'SpeechLib' from 'comtypes.gen' (C:\Users\DC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\comtypes\gen\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\DC\AppData\Local\Programs\Python\Python37-32\lib\ctypes\__init__.py", line 121, in
WINFUNCTYPE
    return _win_functype_cache[(restype, argtypes, flags)]
KeyError: (<class 'ctypes.HRESULT'>, (<class 'comtypes.automation.tagVARIANT'>,), 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:/vilas/chatgpt/gpt.py", line 7, in <module>
    engine = pyttsx3.init()
  File "C:\Users\DC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyttsx3\__init__.py", line 22, in init
    eng = Engine(driverName, debug)
  File "C:\Users\DC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyttsx3\engine.py",
line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "C:\Users\DC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyttsx3\driver.py",
line 50, in __init__
    self._module = importlib.import_module(name)
  File "C:\Users\DC\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127,
in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\DC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyttsx3\drivers\sapi5.py", line 6, in <module>
    engine = comtypes.client.CreateObject("SAPI.SpVoice")
  File "C:\Users\DC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\comtypes\client\__init__.py", line 227, in CreateObject
    return _manage(obj, clsid, interface=interface)
  File "C:\Users\DC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\comtypes\client\__init__.py", line 165, in _manage
    obj = GetBestInterface(obj)
  File "C:\Users\DC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\comtypes\client\__init__.py", line 111, in GetBestInterface
    mod = GetModule(tlib)
  File "C:\Users\DC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\comtypes\client\_generate.py", line 142, in GetModule
    mod = _create_wrapper_module(tlib, pathname)
  File "C:\Users\DC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\comtypes\client\_generate.py", line 250, in _create_wrapper_module
    mod = _my_import(fullname)
  File "C:\Users\DC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\comtypes\client\_generate.py", line 36, in _my_import
    return importlib.import_module(fullname)
  File "C:\Users\DC\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127,
in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\DC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\comtypes\gen\_C866CA3A_32F7_11D2_9602_00C04F8EE628_0_5_4.py", line 510, in <module>
    (['in'], VARIANT, 'ExtraData')
  File "C:\Users\DC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\comtypes\__init__.py", line 328, in __setattr__
    self._make_methods(value)
  File "C:\Users\DC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\comtypes\__init__.py", line 697, in _make_methods
    prototype = WINFUNCTYPE(restype, *argtypes)
  File "C:\Users\DC\AppData\Local\Programs\Python\Python37-32\lib\ctypes\__init__.py", line 123, in
WINFUNCTYPE
    class WinFunctionType(_CFuncPtr):
TypeError: item 1 in _argtypes_ passes a union by value, which is unsupported.

**Comment by Jiangshan00001** [comment]
it seems that you have a old package list.
could you run pip freeze to show your package version list?
