### ISSUE TITLE
Not working pyttsx3 with python 3.11.4

### ISSUE THREAD

**Issue by Fledermaus-20** [nateshmbhat/pyttsx3#286]
I own a macbook air m2 16 gb ram and 512gb storage
mac os 13.5 
python v. 3.11.4

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyttsx3/drivers/nsss.py:12: ObjCSuperWarning: Objective-C subclass uses super(), but super is not objc.super
  class NSSpeechDriver(NSObject):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyttsx3/__init__.py", line 20, in init
    eng = _activeEngines[driverName]
          ~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/weakref.py", line 136, in __getitem__
    o = self.data[key]()
        ~~~~~~~~~^^^^^
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/username/Library/Mobile Documents/com~apple~CloudDocs/Coding/Sprach Assistent/test.py", line 3, in <module>
    engine = pyttsx3.init()
             ^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyttsx3/__init__.py", line 22, in init
    eng = Engine(driverName, debug)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyttsx3/engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyttsx3/driver.py", line 52, in __init__
    self._driver = self._module.buildDriver(weakref.proxy(self))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyttsx3/drivers/nsss.py", line 9, in buildDriver
    return NSSpeechDriver.alloc().initWithProxy(proxy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyttsx3/drivers/nsss.py", line 15, in initWithProxy
    self = super(NSSpeechDriver, self).init()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'super' object has no attribute 'init'
sys:1: UninitializedDeallocWarning: leaking an uninitialized object of type NSSpeechDriver

**Comment by essenciary** [comment]
Found the solution on SO - you need to replace the faulty line (`nsss.py:15`) by this: 
```python
self = objc.super(NSSpeechDriver, self).init()
```

Also make sure that `pyobjc` is installed as a dependency. 

This fixed it for me, though I'm facing a different issue now: after speaking, the script/app exits.

**Comment by Fledermaus-20** [comment]
Is that the same issue what you hvae found?
Python[11740:160581] -[OC_BuiltinPythonArray hasPrefix:]: unrecognized selector sent to instance 0x11c10d270

**Comment by KerstinCakeHome** [comment]
I have the same Problem and even have the MacBook Air M2. Do you have an Solution for the Problem?
This is my Error:
/Users/kerstingranowski/PycharmProjects/TagNachtDetektor/venv/lib/python3.11/site-packages/pyttsx3/drivers/nsss.py:12: ObjCSuperWarning: Objective-C subclass uses super(), but super is not objc.super
  class NSSpeechDriver(NSObject):
Traceback (most recent call last):
  File "/Users/kerki/PycharmProjects/Taor/venv/lib/python3.11/site-packages/pyttsx3/__init__.py", line 20, in init
    eng = _activeEngines[driverName]
          ~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/weakref.py", line 136, in __getitem__
    o = self.data[key]()
        ~~~~~~~~~^^^^^
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/keski/PycharmProjects/Tagtor/Hauptfenster.py", line 164, in <module>
    speak(text_to_speak)
  File "/Users/kki/PycharmProjects/Tagr/Hauptfenster.py", line 159, in speak
    engine = pyttsx3.init()
             ^^^^^^^^^^^^^^
  File "/Users/kerki/PycharmProjects/Taor/venv/lib/python3.11/site-packages/pyttsx3/__init__.py", line 22, in init
    eng = Engine(driverName, debug)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/keri/PycharmProjects/Tagor/venv/lib/python3.11/site-packages/pyttsx3/engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kersi/PycharmProjects/Taor/venv/lib/python3.11/site-packages/pyttsx3/driver.py", line 52, in __init__
    self._driver = self._module.buildDriver(weakref.proxy(self))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ker/PycharmProjects/Taktor/venv/lib/python3.11/site-packages/pyttsx3/drivers/nsss.py", line 9, in buildDriver
    return NSSpeechDriver.alloc().initWithProxy(proxy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kersting/PycharmProjects/Tktor/venv/lib/python3.11/site-packages/pyttsx3/drivers/nsss.py", line 15, in initWithProxy
    self = super(NSSpeechDriver, self).init()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'super' object has no attribute 'init'
sys:1: UninitializedDeallocWarning: leaking an uninitialized object of type NSSpeechDriver

**Comment by m1guelperez** [comment]
> This fixed it for me, though I'm facing a different issue now: after speaking, the script/app exits.

Wow. Just saw this. Do you mean it exits without any error or status code whatever? As soon as it talked in my case it just terminates without any info.

I tried to trace it down and it seems that in the file 

`def runConsoleEventLoop(
    argv=None, installInterrupt=False, mode=NSDefaultRunLoopMode, maxTimeout=3.0
):
    if argv is None:
        argv = sys.argv
    if installInterrupt:
        installMachInterrupt()
    runLoop = NSRunLoop.currentRunLoop()
    stopper = PyObjCAppHelperRunLoopStopper.alloc().init()
    PyObjCAppHelperRunLoopStopper.addRunLoopStopper_toRunLoop_(stopper, runLoop)
    try:
        while stopper.shouldRun():
            print("shouldRun " + str(stopper.shouldRun()))
            nextfire = runLoop.limitDateForMode_(mode)
            if not stopper.shouldRun():
                print("stopper.shouldRun() is false")
                break

            soon = NSDate.dateWithTimeIntervalSinceNow_(maxTimeout)
            if nextfire is not None:
                nextfire = soon.earlierDate_(nextfire)
                print("nextfire")
            if not runLoop.runMode_beforeDate_(mode, nextfire):
                print("runloop stopped")
                print(runLoop.runMode_beforeDate_(mode, nextfire))
                stopper.stop()
        print("done")
    finally:
        print("finally")
        PyObjCAppHelperRunLoopStopper.removeRunLoopStopperFromRunLoop_(runLoop)`
        
        
        This code never prints `finally` nor `done`. The output is just:
        `shouldRun True
nextfire
shouldRun True
nextfire
shouldRun True
nextfire`

And then it seems to abruptly terminate. However, if we would exit the while loop correctly we would print the `done`.

**Comment by essenciary** [comment]
@m1guelperez Yes, indeed, it just exited without any info/output, practically crashing the app. 

I did manage to make it work (somewhat) by downgrading, but then I ran into another issue when attempting to save as audio files: the audio file was generated but was always the same size (I think 16KB) and empty. 

I was running the script on an M2 aarm mac.

**Comment by ganeshnikhil** [comment]
i am on macos and using python 3.9.0 64 bit . is there any solution for this. 

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyttsx3/__init__.py", line 20, in init
    eng = _activeEngines[driverName]
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/weakref.py", line 134, in __getitem__
    o = self.data[key]()
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Shared/python_code/youtube_summarizer/test.py", line 15, in <module>
    text_to_speech(text)
  File "/Users/Shared/python_code/youtube_summarizer/test.py", line 5, in text_to_speech
    speaker = pyttsx3.init()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyttsx3/__init__.py", line 22, in init
    eng = Engine(driverName, debug)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyttsx3/engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyttsx3/driver.py", line 50, in __init__
    self._module = importlib.import_module(name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyttsx3/drivers/nsss.py", line 12, in <module>
    class NSSpeechDriver(NSObject):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyttsx3/drivers/nsss.py", line 13, in NSSpeechDriver
    @objc.python_method
NameError: name 'objc' is not defined

**Comment by Fledermaus-20** [comment]
#297
