### ISSUE TITLE
pyttsx3 not working with python 3.11

### ISSUE THREAD

**Issue by SaiAnirudh659** [nateshmbhat/pyttsx3#304]
I have a problem with pyttsx3 working with python 3.11

Traceback (most recent call last):
  File "/Users/anirudh/Desktop/pythonProject4/.venv/lib/python3.11/site-packages/pyttsx3/__init__.py", line 20, in init
    eng = _activeEngines[driverName]
          ~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/weakref.py", line 136, in __getitem__
    o = self.data[key]()
        ~~~~~~~~~^^^^^
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/anirudh/Desktop/pythonProject4/text to speech.py", line 5, in <module>
    text_speech = pyttsx3.init()
                  ^^^^^^^^^^^^^^
  File "/Users/anirudh/Desktop/pythonProject4/.venv/lib/python3.11/site-packages/pyttsx3/__init__.py", line 22, in init
    eng = Engine(driverName, debug)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anirudh/Desktop/pythonProject4/.venv/lib/python3.11/site-packages/pyttsx3/engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anirudh/Desktop/pythonProject4/.venv/lib/python3.11/site-packages/pyttsx3/driver.py", line 50, in __init__
    self._module = importlib.import_module(name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/anirudh/Desktop/pythonProject4/.venv/lib/python3.11/site-packages/pyttsx3/drivers/nsss.py", line 12, in <module>
    class NSSpeechDriver(NSObject):
  File "/Users/anirudh/Desktop/pythonProject4/.venv/lib/python3.11/site-packages/pyttsx3/drivers/nsss.py", line 13, in NSSpeechDriver
    @object.python_method
     ^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'object' has no attribute 'python_method'

**Comment by willwade** [comment]
This fork fixes this https://github.com/thevickypedia/py3-tts

**Comment by willwade** [comment]
Im pretty sure @nateshmbhat you can close this now
