### ISSUE TITLE
pyttsx3 run time issue

### ISSUE THREAD

**Issue by saitej414** [nateshmbhat/pyttsx3#49]
I am using windows while trying to execute got this error can anyone help 

import pyttsx3
pyttsx3.__init__()

D:\pythanpractice\venv\Scripts\python.exe D:/pythanpractice/speach2text.py
Traceback (most recent call last):
  File "D:\pythanpractice\venv\lib\site-packages\pyttsx3\__init__.py", line 20, in init
    eng = _activeEngines[driverName]
  File "C:\Users\saite\AppData\Local\Programs\Python\Python36\lib\weakref.py", line 137, in __getitem__
    o = self.data[key]()
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/pythanpractice/speach2text.py", line 12, in <module>
    pyttsx3.init()
  File "D:\pythanpractice\venv\lib\site-packages\pyttsx3\__init__.py", line 22, in init
    eng = Engine(driverName, debug)
  File "D:\pythanpractice\venv\lib\site-packages\pyttsx3\engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "D:\pythanpractice\venv\lib\site-packages\pyttsx3\driver.py", line 50, in __init__
    self._module = importlib.import_module(name)
  File "C:\Users\saite\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\pythanpractice\venv\lib\site-packages\pyttsx3\drivers\sapi5.py", line 3, in <module>
    import win32com.client
  File "D:\pythanpractice\venv\lib\site-packages\win32com\client\__init__.py", line 11, in <module>
    from . import gencache
  File "D:\pythanpractice\venv\lib\site-packages\win32com\client\gencache.py", line 660, in <module>
    __init__()
  File "D:\pythanpractice\venv\lib\site-packages\win32com\client\gencache.py", line 60, in __init__
    _LoadDicts()
  File "D:\pythanpractice\venv\lib\site-packages\win32com\client\gencache.py", line 113, in _LoadDicts
    version = p.load()
_pickle.UnpicklingError: invalid load key, '\x00'.

Process finished with exit code 1

**Comment by Kerang** [comment]
This is a minimum example:
```
import pyttsx3

engine = pyttsx3.init()
engine.say("I will speak this text")
engine.runAndWait()
```
