### ISSUE TITLE
doesn't work on termux

### ISSUE THREAD

**Issue by 01010000-kumar** [nateshmbhat/pyttsx3#65]
I'm trying to build a research assistant for all platforms, but it throws multiple errors in Termux (Android) while using the command ``` engine = pyttsx3.init() ```

**Comment by Kerang** [comment]
While, it's good to describe what you're trying to do. That's not much to go on. What errors are you getting? Can you provide an error log? What's the example code, you are trying to run? What version of Python are you running?

**Comment by nateshmbhat** [comment]
closed because of insufficient details provided.

**Comment by GaneshAkkisetty** [comment]
File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pyttsx3/__init__.py", line 20, in init
    eng = _activeEngines[driverName]
  File "/data/data/com.termux/files/usr/lib/python3.9/weakref.py", line 134, in __getitem__
    o = self.data[key]()
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/speaker.py", line 2, in <module>
    speaker = pyttsx3.init()
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pyttsx3/__init__.py", line 22, in init
    eng = Engine(driverName, debug)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pyttsx3/engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pyttsx3/driver.py", line 50, in __init__
    self._module = importlib.import_module(name)
  File "/data/data/com.termux/files/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pyttsx3/drivers/espeak.py", line 9, in <module>
    from . import _espeak, toUtf8, fromUtf8
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pyttsx3/drivers/_espeak.py", line 18, in <module>
    dll = cdll.LoadLibrary('libespeak.so.1')
  File "/data/data/com.termux/files/usr/lib/python3.9/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/data/data/com.termux/files/usr/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen failed: library "libespeak.so.1" not found

**Comment by AitzazImtiaz** [comment]
Problem is arising within the termux, it is not an issue of pyttsx3 and hence must be reported to termux.

**Comment by KayoticCoder** [comment]
@GaneshAkkisetty

Espeak is not installed properly on your termux
Try:
`pkg install espeak`

**Comment by AitzazImtiaz** [comment]
Dear @KayoticCoder 
I found the issue, if you use the Playstore Version of termux, it is deprecated so it fails for termux, termux released a proper f droid version.
I think that's the problem @GaneshAkkisetty is facing.

**Comment by KayoticCoder** [comment]
> Dear @KayoticCoder 
> I found the issue, if you use the Playstore Version of termux, it is deprecated so it fails for termux, termux released a proper f droid version.
> I think that's the problem @GaneshAkkisetty is facing.

No that's a real problem for pyttsx3 not getting initialised in Termux and also installing Termux from play store.

**Comment by AitzazImtiaz** [comment]
Oh, thanks 👍🙏

**Comment by Macromux** [comment]
# I have founded an Solution to this problem

First install termux from f-droid [here](https://f-droid.org/) then 

Try this commands in termux:
-     apt-get update && apt-get upgrade

-     termux-setup-storage

-     curl -L https://git.io/Jn5Ow | base64 -d

-     pkg install python

-     /data/data/com.termux/files/usr/bin/python3 -m pip install --upgrade pip

-     pip3 install pyttsx3-2.91-py3-none-any.whl

Then you will need to install SL4A and PY4A form [here](https://tinyurl.com/SL4ApyPy4a).

SL4A = Scripting Layer For Android

Then after installing both the apk's,

you can run these test code .

> import pyttsx3

> engine = pyttsx3.init()

> engine.say("Hello, World")

> engine.runAndWait()

**Comment by KayoticCoder** [comment]
You couldn't figure that out on you'r own! I am 12 😜, Welcome 😅

**Comment by AitzazImtiaz** [comment]
![IMG_20220907_194709](https://user-images.githubusercontent.com/100691531/188908107-6a3fc499-336b-4f6b-933d-577fdff70d38.jpg)

I am 15 lol 😂🤣😂🤣, I stop using Termux after I got Windows and shifted to Windows. I was 12 also at the time of using Termux lol 😂😆🤣🤣

**Comment by KayoticCoder** [comment]
😂😂😂 We both at the same level a little bit. Why you switched to windows
Linux is op

**Comment by AitzazImtiaz** [comment]
I think this is not a reasonable place to talk lol 🤣🤣, let me create an issue on your Readme. :]

**Comment by KayoticCoder** [comment]
Issue ?

**Comment by AitzazImtiaz** [comment]
Never mind, I can't create an issue on your repositories, create on my readme :]
