### ISSUE TITLE
Error while running basic program on Raspberry Pi

### ISSUE THREAD

**Issue by salmanfarisvp** [nateshmbhat/pyttsx3#70]
System : Raspberry Pi B+
OS : Raspbian 

Installed pyttsx3 via pip  `pip install pyttsx3`

**Programme**:

```
import pyttsx3
engine = pyttsx3.init()
engine.say("I will speak this text")
engine.runAndWait() 
```

**Error**
```
Traceback (most recent call last):
  File "/home/pi/.virtualenvs/cv/local/lib/python3.7/site-packages/pyttsx3/__init__.py", line 20, in init
    eng = _activeEngines[driverName]
  File "/home/pi/.virtualenvs/cv/lib/python3.7/weakref.py", line 137, in __getitem__
    o = self.data[key]()
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "text.py", line 2, in <module>
    engine = pyttsx3.init()
  File "/home/pi/.virtualenvs/cv/local/lib/python3.7/site-packages/pyttsx3/__init__.py", line 22, in init
    eng = Engine(driverName, debug)
  File "/home/pi/.virtualenvs/cv/local/lib/python3.7/site-packages/pyttsx3/engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "/home/pi/.virtualenvs/cv/local/lib/python3.7/site-packages/pyttsx3/driver.py", line 50, in __init__
    self._module = importlib.import_module(name)
  File "/home/pi/.virtualenvs/cv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pi/.virtualenvs/cv/local/lib/python3.7/site-packages/pyttsx3/drivers/espeak.py", line 5, in <module>
    from . import _espeak, toUtf8, fromUtf8
  File "/home/pi/.virtualenvs/cv/local/lib/python3.7/site-packages/pyttsx3/drivers/_espeak.py", line 18, in <module>
    dll = cdll.LoadLibrary('libespeak.so.1')
  File "/usr/lib/python3.7/ctypes/__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libespeak.so.1: cannot open shared object file: No such file or directory
```

**Comment by GopikrishnanSasikumar** [comment]
Try installing espeak.

```
sudo apt-get update && sudo apt-get install espeak
```

**Comment by salmanfarisvp** [comment]
@GopikrishnanSasikumar  I alredy Installed **espeak** 

```
Reading package lists... Done
Building dependency tree
Reading state information... Done
espeak is already the newest version (1.48.04+dfsg-7).
0 upgraded, 0 newly installed, 0 to remove and 200 not upgraded.
```

**Comment by GopikrishnanSasikumar** [comment]
Try 
```
sudo apt install libespeak1
```

**Comment by salmanfarisvp** [comment]
it's also the newest version,

s```
udo apt install libespeak1
Reading package lists... Done
Building dependency tree
Reading state information... Done
libespeak1 is already the newest version (1.48.04+dfsg-7).
0 upgraded, 0 newly installed, 0 to remove and 200 not upgraded. 


```

**Comment by salmanfarisvp** [comment]
```
 sudo apt-get install python-espeak
Reading package lists... Done
Building dependency tree
Reading state information... Done
python-espeak is already the newest version (0.5-1+b4).
0 upgraded, 0 newly installed, 0 to remove and 200 not upgraded.
```

**Comment by Kerang** [comment]
Try taking a look at this closed issue? https://github.com/nateshmbhat/pyttsx3/issues/45

**Comment by nateshmbhat** [comment]
@salmanfarisvp  did installing libspeak fix this issue ?

**Comment by nateshmbhat** [comment]
The below fix should fix this issue :

https://github.com/nateshmbhat/pyttsx3/issues/38#issuecomment-599006878
