### ISSUE TITLE
pyttsx3

### ISSUE THREAD

**Issue by Satheesh332** [nateshmbhat/pyttsx3#80]
While running the program, the following error pops-up:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pyttsx3'
 
But I installed pyttsx3 along with pywin32... I'm new to programming. I don't know how to solve this. I'm in need of help!

**Comment by alexander-e-andrews** [comment]
Can you attach your code example?
