### ISSUE TITLE
Can't install on Arch Linux

### ISSUE THREAD

**Issue by gaetan1903** [nateshmbhat/pyttsx3#83]
I try to install with pip : `$ sudo pip install pyttsx3` but it returned error. I've tried with python3.8 and python3.7 but it's the same errors:

_ERROR: Command errored out with exit status 1:
     command: /home/hck1903/environnement/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-k7ctsy2p/pyobjc-framework-CoreServices/setup.py'"'"'; __file__='"'"'/tmp/pip-install-k7ctsy2p/pyobjc-framework-CoreServices/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-k7ctsy2p/pyobjc-framework-CoreServices/pip-egg-info
         cwd: /tmp/pip-install-k7ctsy2p/pyobjc-framework-CoreServices/
    Complete output (15 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-k7ctsy2p/pyobjc-framework-CoreServices/setup.py", line 28, in <module>
        extra_link_args=["-framework", "CoreServices"],
      File "/tmp/pip-install-k7ctsy2p/pyobjc-framework-CoreServices/pyobjc_setup.py", line 408, in Extension
        os_level = get_os_level()
      File "/tmp/pip-install-k7ctsy2p/pyobjc-framework-CoreServices/pyobjc_setup.py", line 218, in get_os_level
        pl = plistlib.readPlist("/System/Library/CoreServices/SystemVersion.plist")
      File "/home/hck1903/environnement/anaconda3/lib/python3.7/plistlib.py", line 99, in readPlist
        with _maybe_open(pathOrFile, 'rb') as fp:
      File "/home/hck1903/environnement/anaconda3/lib/python3.7/contextlib.py", line 112, in __enter__
        return next(self.gen)
      File "/home/hck1903/environnement/anaconda3/lib/python3.7/plistlib.py", line 82, in _maybe_open
        with open(pathOrFile, mode) as fp:
    FileNotFoundError: [Errno 2] No such file or directory: '/System/Library/CoreServices/SystemVersion.plist'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output._

**Comment by sandervalstar** [comment]
I'm experiencing similar issues on Ubuntu. It seems like a dependency on pyobj packages was introduced for the linux version of pyttx3, but those can only be installed on Mac.

**Comment by sandervalstar** [comment]
Workaround for now is to install an older version:
`pip3 install pyttsx3==2.71`

**Comment by gaetan1903** [comment]
okey, thanks it works  👏 👍
