### ISSUE TITLE
A lot of Errors!

### ISSUE THREAD

**Issue by AmitKarnam** [nateshmbhat/pyttsx3#99]
Traceback (most recent call last):
  File "C:\Users\amitk\Desktop\Python\pyttsx3\__init__.py", line 20, in init
    eng = _activeEngines[driverName]
  File "C:\Users\amitk\Desktop\Python\lib\weakref.py", line 131, in __getitem__
    o = self.data[key]()
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\amitk\Desktop\Python\pyttsx3\drivers\sapi5.py", line 3, in <module>
    from comtypes.gen import SpeechLib  # comtypes
ImportError: cannot import name 'SpeechLib' from 'comtypes.gen' (C:\Users\amitk\AppData\Roaming\Python\Python38\site-packages\comtypes\gen\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\amitk\Desktop\Python\lib\ctypes\__init__.py", line 123, in WINFUNCTYPE
    return _win_functype_cache[(restype, argtypes, flags)]
KeyError: (<class 'ctypes.HRESULT'>, (<class 'comtypes.automation.tagVARIANT'>, <class 'comtypes.LP_POINTER(ISpeechRecoGrammar)'>), 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/amitk/Desktop/PYTHON_CODES/Telusko Tutorial codes/JARVIS.py", line 5, in <module>
    engine = pyttsx3.init(driverName=None,debug=False)
  File "C:\Users\amitk\Desktop\Python\pyttsx3\__init__.py", line 22, in init
    eng = Engine(driverName, debug)
  File "C:\Users\amitk\Desktop\Python\pyttsx3\engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "C:\Users\amitk\Desktop\Python\pyttsx3\driver.py", line 50, in __init__
    self._module = importlib.import_module(name)
  File "C:\Users\amitk\Desktop\Python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\amitk\Desktop\Python\pyttsx3\drivers\sapi5.py", line 6, in <module>
    engine = comtypes.client.CreateObject("SAPI.SpVoice")
  File "C:\Users\amitk\AppData\Roaming\Python\Python38\site-packages\comtypes\client\__init__.py", line 250, in CreateObject
    return _manage(obj, clsid, interface=interface)
  File "C:\Users\amitk\AppData\Roaming\Python\Python38\site-packages\comtypes\client\__init__.py", line 188, in _manage
    obj = GetBestInterface(obj)
  File "C:\Users\amitk\AppData\Roaming\Python\Python38\site-packages\comtypes\client\__init__.py", line 110, in GetBestInterface
    mod = GetModule(tlib)
  File "C:\Users\amitk\AppData\Roaming\Python\Python38\site-packages\comtypes\client\_generate.py", line 110, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "C:\Users\amitk\AppData\Roaming\Python\Python38\site-packages\comtypes\client\_generate.py", line 184, in _CreateWrapper
    mod = _my_import(fullname)
  File "C:\Users\amitk\AppData\Roaming\Python\Python38\site-packages\comtypes\client\_generate.py", line 24, in _my_import
    return __import__(fullname, globals(), locals(), ['DUMMY'])
  File "C:\Users\amitk\AppData\Roaming\Python\Python38\site-packages\comtypes\gen\_C866CA3A_32F7_11D2_9602_00C04F8EE628_0_5_4.py", line 242, in <module>
    ISpeechRecoContext._methods_ = [
  File "C:\Users\amitk\AppData\Roaming\Python\Python38\site-packages\comtypes\__init__.py", line 329, in __setattr__
    self._make_methods(value)
  File "C:\Users\amitk\AppData\Roaming\Python\Python38\site-packages\comtypes\__init__.py", line 698, in _make_methods
    prototype = WINFUNCTYPE(restype, *argtypes)
  File "C:\Users\amitk\Desktop\Python\lib\ctypes\__init__.py", line 125, in WINFUNCTYPE
    class WinFunctionType(_CFuncPtr):
TypeError: item 1 in _argtypes_ passes a union by value, which is unsupported.

Process finished with exit code 1

**Comment by AmitKarnam** [comment]
Traceback (most recent call last):
  File "C:\Users\amitk\Desktop\Python\pyttsx3\__init__.py", line 20, in init
    eng = _activeEngines[driverName]
  File "C:\Users\amitk\Desktop\Python\lib\weakref.py", line 131, in __getitem__
    o = self.data[key]()
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\amitk\Desktop\Python\pyttsx3\drivers\sapi5.py", line 3, in <module>
    from comtypes.gen import SpeechLib  # comtypes
ImportError: cannot import name 'SpeechLib' from 'comtypes.gen' (C:\Users\amitk\AppData\Roaming\Python\Python38\site-packages\comtypes\gen\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\amitk\Desktop\Python\lib\ctypes\__init__.py", line 123, in WINFUNCTYPE
    return _win_functype_cache[(restype, argtypes, flags)]
KeyError: (<class 'ctypes.HRESULT'>, (<class 'comtypes.automation.tagVARIANT'>, <class 'comtypes.LP_POINTER(ISpeechRecoGrammar)'>), 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/amitk/Desktop/PYTHON_CODES/Telusko Tutorial codes/JARVIS.py", line 5, in <module>
    engine = pyttsx3.init(driverName=None,debug=False)
  File "C:\Users\amitk\Desktop\Python\pyttsx3\__init__.py", line 22, in init
    eng = Engine(driverName, debug)
  File "C:\Users\amitk\Desktop\Python\pyttsx3\engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "C:\Users\amitk\Desktop\Python\pyttsx3\driver.py", line 50, in __init__
    self._module = importlib.import_module(name)
  File "C:\Users\amitk\Desktop\Python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\amitk\Desktop\Python\pyttsx3\drivers\sapi5.py", line 6, in <module>
    engine = comtypes.client.CreateObject("SAPI.SpVoice")
  File "C:\Users\amitk\AppData\Roaming\Python\Python38\site-packages\comtypes\client\__init__.py", line 250, in CreateObject
    return _manage(obj, clsid, interface=interface)
  File "C:\Users\amitk\AppData\Roaming\Python\Python38\site-packages\comtypes\client\__init__.py", line 188, in _manage
    obj = GetBestInterface(obj)
  File "C:\Users\amitk\AppData\Roaming\Python\Python38\site-packages\comtypes\client\__init__.py", line 110, in GetBestInterface
    mod = GetModule(tlib)
  File "C:\Users\amitk\AppData\Roaming\Python\Python38\site-packages\comtypes\client\_generate.py", line 110, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "C:\Users\amitk\AppData\Roaming\Python\Python38\site-packages\comtypes\client\_generate.py", line 184, in _CreateWrapper
    mod = _my_import(fullname)
  File "C:\Users\amitk\AppData\Roaming\Python\Python38\site-packages\comtypes\client\_generate.py", line 24, in _my_import
    return __import__(fullname, globals(), locals(), ['DUMMY'])
  File "C:\Users\amitk\AppData\Roaming\Python\Python38\site-packages\comtypes\gen\_C866CA3A_32F7_11D2_9602_00C04F8EE628_0_5_4.py", line 242, in <module>
    ISpeechRecoContext._methods_ = [
  File "C:\Users\amitk\AppData\Roaming\Python\Python38\site-packages\comtypes\__init__.py", line 329, in __setattr__
    self._make_methods(value)
  File "C:\Users\amitk\AppData\Roaming\Python\Python38\site-packages\comtypes\__init__.py", line 698, in _make_methods
    prototype = WINFUNCTYPE(restype, *argtypes)
  File "C:\Users\amitk\Desktop\Python\lib\ctypes\__init__.py", line 125, in WINFUNCTYPE
    class WinFunctionType(_CFuncPtr):
TypeError: item 1 in _argtypes_ passes a union by value, which is unsupported.

Process finished with exit code 1

**Comment by nateshmbhat** [comment]
People using python3.8 are reporting errors regarding this. See #101 too.

try installing pyttsx3 version 2.71

**Comment by AmitKarnam** [comment]
Hey Nateshmbhat,
Thanks for your input, the module worked as expected without any error.

**Comment by nateshmbhat** [comment]
Can u Please tell which changes u made to make it work?

Did u install version 2.71 ?

**Comment by PalmtopTiger** [comment]
@nateshmbhat 
Apparently, commits between Jan 24, 2020 and Mar 14, 2020 disappeared from the master branch.
I see some [pull requests](https://github.com/nateshmbhat/pyttsx3/pulls?q=is%3Apr+is%3Aclosed) merged during this time that fix, for example, an error with installation on Windows (#89). These changes are not in the current code.
There are also no tags between v2.7 and v2.84.
I have version 2.81 on Python 3.8.2 - everything works fine. Its code contains changes from [this commit](https://github.com/nateshmbhat/pyttsx3/pull/89/commits/e529301a0e40b54299d6242e1a8cb52261471880) that are not in master.

**Comment by nateshmbhat** [comment]
Is it better if I revert all the commits back to this merge commit ? https://github.com/nateshmbhat/pyttsx3/pull/89/commits/e529301a0e40b54299d6242e1a8cb52261471880

**Comment by PalmtopTiger** [comment]
What actually happened? Why were commits gone?
I think you should revert to the latest working version - 2.81 ([Feb 1, 2020](https://pypi.org/project/pyttsx3/#history)). I don’t know which commit it was, I did not follow the project.

**Comment by nateshmbhat** [comment]
I have applied the fix for this issue : Latest release is 2.87.
Just install the latest release with `pip install pyttsx3` and please let me know if it fixed the issue.

**Comment by ethanvoo** [comment]
It still gives an error when I run the example code u give. this is the error

Traceback (most recent call last):
  File "/home/ethan/lib/python3.7/site-packages/pyttsx3/__init__.py", line 20, in init
    eng = _activeEngines[driverName]
  File "/home/ethan/lib64/python3.7/weakref.py", line 137, in __getitem__
    o = self.data[key]()
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ethan/PycharmProjects/Jarvis/main.py", line 3, in <module>
    engine = pyttsx3.init()  # object creation
  File "/home/ethan/lib/python3.7/site-packages/pyttsx3/__init__.py", line 22, in init
    eng = Engine(driverName, debug)
  File "/home/ethan/lib/python3.7/site-packages/pyttsx3/engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "/home/ethan/lib/python3.7/site-packages/pyttsx3/driver.py", line 50, in __init__
    self._module = importlib.import_module(name)
  File "/home/ethan/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ethan/lib/python3.7/site-packages/pyttsx3/drivers/espeak.py", line 5, in <module>
    from . import _espeak, toUtf8, fromUtf8
  File "/home/ethan/lib/python3.7/site-packages/pyttsx3/drivers/_espeak.py", line 18, in <module>
    dll = cdll.LoadLibrary('libespeak.so.1')
  File "/usr/lib64/python3.7/ctypes/__init__.py", line 437, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib64/python3.7/ctypes/__init__.py", line 359, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libespeak.so.1: cannot open shared object file: No such file or directory

Process finished with exit code 1

**Comment by FUNKY-doc69** [comment]
@ethanvoo you have to install libespeak for that error i think try doing that
sudo apt install libespeak1

**Comment by FUNKY-doc69** [comment]
hey and i am getting this error for the trial code
Traceback (most recent call last):
  File "C:\Users\adwai\AppData\Local\Programs\Python\Python38\lib\site-packages\pyttsx3\__init__.py", line 20, in init
    eng = _activeEngines[driverName]
  File "C:\Users\adwai\AppData\Local\Programs\Python\Python38\lib\weakref.py", line 131, in __getitem__
    o = self.data[key]()
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "i:\Code Files\Python\tts\1.py", line 3, in <module>
    engine = pyttsx3.init()
  File "C:\Users\adwai\AppData\Local\Programs\Python\Python38\lib\site-packages\pyttsx3\__init__.py", line 22, in init
    eng = Engine(driverName, debug)
  File "C:\Users\adwai\AppData\Local\Programs\Python\Python38\lib\site-packages\pyttsx3\engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "C:\Users\adwai\AppData\Local\Programs\Python\Python38\lib\site-packages\pyttsx3\driver.py", line 50, in __init__
    self._module = importlib.import_module(name)
  File "C:\Users\adwai\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\adwai\AppData\Local\Programs\Python\Python38\lib\site-packages\pyttsx3\drivers\sapi5.py", line 3, in <module>
    import win32com.client
  File "C:\Users\adwai\AppData\Roaming\Python\Python38\site-packages\win32com\__init__.py", line 5, in <module>
    import win32api, sys, os
ImportError: DLL load failed while importing win32api: %1 is not a valid Win32 application.

**Comment by FUNKY-doc69** [comment]
okay so installing the pyttsx3 version 2.71 along with reinstalling pywin32 and pypiwin32 helped with the working of the module. The voice is great. @nateshmbhat thanks

**Comment by ethanvoo** [comment]
Thanks a lot. :)

**Comment by BergisBlood** [comment]
**POR FAVOR AYUDA!! TENGO ESTE PROBLEMA CON PYTHON**
----------------------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\gisve\AppData\Local\Programs\Python\Python38\lib\site-packages\pyttsx3\__init__.py", line 20, in init
    eng = _activeEngines[driverName]
  File "C:\Users\gisve\AppData\Local\Programs\Python\Python38\lib\weakref.py", line 131, in __getitem__
    o = self.data[key]()
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gisve\AppData\Local\Programs\Python\Python38\asistente\asistente.py", line 5, in <module>
    engineio = pyttsx3.init()
  File "C:\Users\gisve\AppData\Local\Programs\Python\Python38\lib\site-packages\pyttsx3\__init__.py", line 22, in init
    eng = Engine(driverName, debug)
  File "C:\Users\gisve\AppData\Local\Programs\Python\Python38\lib\site-packages\pyttsx3\engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "C:\Users\gisve\AppData\Local\Programs\Python\Python38\lib\site-packages\pyttsx3\driver.py", line 50, in __init__
    self._module = importlib.import_module(name)
  File "C:\Users\gisve\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\gisve\AppData\Local\Programs\Python\Python38\lib\site-packages\pyttsx3\drivers\sapi5.py", line 10, in <module>
    import pythoncom
  File "C:\Users\gisve\AppData\Local\Programs\Python\Python38\lib\site-packages\pythoncom.py", line 2, in <module>
    import pywintypes
ModuleNotFoundError: No module named 'pywintypes'
--------------------------------------------------------------------------------------------------------------------------------------------
mis librerias
altgraph                  0.17
beautifulsoup4            4.9.1
certifi                   2020.6.20
chardet                   3.0.4
click                     7.1.2
comtypes                  1.1.7
cycler                    0.10.0
future                    0.18.2
gTTS                      2.1.1
gTTS-token                1.1.3
idna                      2.10
joblib                    0.16.0
kiwisolver                1.2.0
llvmlite                  0.34.0
matplotlib                3.3.2
numba                     0.51.2
numpy                     1.19.2
pandas                    1.1.2
pefile                    2019.4.18
Pillow                    7.2.0
pip                       20.2.3
PyAudio                   0.2.11
pyinstaller               4.0
pyinstaller-hooks-contrib 2020.8
pyparsing                 2.4.7
pypiwin32                 223
python-dateutil           2.8.1
python-engineio           3.13.2
pyttsx3                   2.90
pytz                      2020.1
pywin32                   228
pywin32-ctypes            0.2.0
requests                  2.24.0
scikit-learn              0.23.2
scipy                     1.5.2
setuptools                50.3.0
shap                      0.36.0
six                       1.15.0
slicer                    0.0.4
soupsieve                 2.0.1
SpeechRecognition         3.8.1
threadpoolctl             2.1.0
tqdm                      4.49.0
urllib3                   1.25.10
wheel                     0.35.1

**Comment by AmitKarnam** [comment]
Try installing the pyttsx3 version 2.71. It worked for me.

**Comment by shreyas1203-gif** [comment]
> ## **POR FAVOR AYUDA!! TENGO ESTE PROBLEMA CON PYTHON**
> Traceback (most recent call last):
> File "C:\Users\gisve\AppData\Local\Programs\Python\Python38\lib\site-packages\pyttsx3__init__.py", line 20, in init
> eng = _activeEngines[driverName]
> File "C:\Users\gisve\AppData\Local\Programs\Python\Python38\lib\weakref.py", line 131, in **getitem**
> o = self.datakey
> KeyError: None
> 
> During handling of the above exception, another exception occurred:
> 
> ## Traceback (most recent call last):
> File "C:\Users\gisve\AppData\Local\Programs\Python\Python38\asistente\asistente.py", line 5, in
> engineio = pyttsx3.init()
> File "C:\Users\gisve\AppData\Local\Programs\Python\Python38\lib\site-packages\pyttsx3__init__.py", line 22, in init
> eng = Engine(driverName, debug)
> File "C:\Users\gisve\AppData\Local\Programs\Python\Python38\lib\site-packages\pyttsx3\engine.py", line 30, in **init**
> self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
> File "C:\Users\gisve\AppData\Local\Programs\Python\Python38\lib\site-packages\pyttsx3\driver.py", line 50, in **init**
> self._module = importlib.import_module(name) File "C:\Users\gisve\AppData\Local\Programs\Python\Python38\lib\importlib__init__.py", line 127, in import_module
> return _bootstrap._gcd_import(name[level:], package, level)
> File "", line 1014, in _gcd_import
> File "", line 991, in _find_and_load
> File "", line 975, in _find_and_load_unlocked
> File "", line 671, in _load_unlocked
> File "", line 783, in exec_module
> File "", line 219, in _call_with_frames_removed
> File "C:\Users\gisve\AppData\Local\Programs\Python\Python38\lib\site-packages\pyttsx3\drivers\sapi5.py", line 10, in
> import pythoncom
> File "C:\Users\gisve\AppData\Local\Programs\Python\Python38\lib\site-packages\pythoncom.py", line 2, in
> import pywintypes
> ModuleNotFoundError: No module named 'pywintypes'
> mis librerias
> altgraph 0.17
> beautifulsoup4 4.9.1
> certifi 2020.6.20
> chardet 3.0.4
> click 7.1.2
> comtypes 1.1.7
> cycler 0.10.0
> future 0.18.2
> gTTS 2.1.1
> gTTS-token 1.1.3
> idna 2.10
> joblib 0.16.0
> kiwisolver 1.2.0
> llvmlite 0.34.0
> matplotlib 3.3.2
> numba 0.51.2
> numpy 1.19.2
> pandas 1.1.2
> pefile 2019.4.18
> Pillow 7.2.0
> pip 20.2.3
> PyAudio 0.2.11
> pyinstaller 4.0
> pyinstaller-hooks-contrib 2020.8
> pyparsing 2.4.7
> pypiwin32 223
> python-dateutil 2.8.1
> python-engineio 3.13.2
> pyttsx3 2.90
> pytz 2020.1
> pywin32 228
> pywin32-ctypes 0.2.0
> requests 2.24.0
> scikit-learn 0.23.2
> scipy 1.5.2
> setuptools 50.3.0
> shap 0.36.0
> six 1.15.0
> slicer 0.0.4
> soupsieve 2.0.1
> SpeechRecognition 3.8.1
> threadpoolctl 2.1.0
> tqdm 4.49.0
> urllib3 1.25.10
> wheel 0.35.1

what is solution on this error

**Comment by willwade** [comment]
Pretty confident now fixed. Use latest release. Please reopen if you see it.
